name: hiyaya
description: Say HiYaYa~ to your friends on LINE with encrypted messages!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  get: ^4.1.4
  flutter_svg: ^0.22.0
  flutter_login: ^2.0.0-nullsafety.0
  rounded_loading_button: ^2.0.4
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/hiyaya512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
